"use client";
import { useState } from "react";
import Link from "next/link";
import { useLocale } from "next-intl";
import { ArrowRight, BookOpen, Clock, Search, ShieldCheck } from "lucide-react";

const posts = [
  { type: "sourcing", image: "/blog-images/IMG_8706.jpg", ar: ["كيف تكتب طلب توريد يمنحك أسعاراً أفضل", "المواصفات الواضحة تختصر وقت البحث وتمنع اختلاف التوقعات مع المورد."], en: ["How to write a sourcing brief that gets better quotes", "Clear specifications shorten research time and prevent mismatched expectations."] },
  { type: "shipping", image: "/blog-images/IMG_8707.jpg", ar: ["بحري أم جوي؟ قرار الشحن يبدأ من طبيعة البضاعة", "قارن السرعة والحجم والمخاطر قبل اختيار وسيلة النقل، لا السعر وحده."], en: ["Sea or air? Choose freight by cargo, not price alone", "Compare speed, volume, and risk before choosing a transport mode."] },
  { type: "quality", image: "/blog-images/IMG_8708.jpg", ar: ["ما الذي يجب أن يتضمنه فحص ما قبل الشحن؟", "قائمة عملية للمواصفات والكمية والتغليف والتوثيق قبل مغادرة البضاعة."], en: ["What should a pre-shipment inspection cover?", "A practical checklist for specifications, quantity, packaging, and documentation."] },
  { type: "customs", image: "/blog-images/IMG_8709.jpg", ar: ["المستندات التي تمنع التأخير في الجمارك", "فهم الفاتورة وقائمة التعبئة ورمز HS يجعل التخليص أكثر قابلية للتوقع."], en: ["The documents that prevent customs delays", "Understanding invoices, packing lists, and HS codes makes clearance predictable."] },
  { type: "warehousing", image: "/blog-images/IMG_8710.jpg", ar: ["متى يكون تجميع الموردين خياراً أفضل؟", "التجميع ليس دائماً الأرخص؛ هذه هي الأسئلة التي تحدد جدواه لشحنتك."], en: ["When does multi-supplier consolidation make sense?", "Consolidation is not always cheaper. These questions reveal when it works."] },
  { type: "sourcing", image: "/blog-images/IMG_8711.jpg", ar: ["خمس إشارات تستحق التدقيق قبل اختيار المورد", "لا يكفي ملف المورد أو الصور. ابحث عن أدلة القدرة والإنتاج والاتساق."], en: ["Five signals to check before choosing a supplier", "A supplier profile and photos are not enough. Look for evidence of capability."] },
  { type: "shipping", image: "/blog-images/IMG_8712.jpg", ar: ["كيف تقلل تكلفة الشحن من الصين", "استراتيجيات عملية لتقليل تكاليف الشحن البحري والجوي من الصين."], en: ["How to reduce shipping costs from China", "Practical strategies to reduce sea and air shipping costs from China."] },
  { type: "quality", image: "/blog-images/IMG_8713.jpg", ar: ["أهمية فحص الجودة في المصنع", "لماذا يجب عليك فحص المنتجات في المصنع قبل الشحن."], en: ["The importance of factory quality inspection", "Why you should inspect products at the factory before shipping."] },
  { type: "customs", image: "/blog-images/IMG_8714.jpg", ar: ["دليل التخليص الجمركي في السعودية", "كل ما تحتاج معرفته عن التخليص الجمركي للبضائع المستوردة."], en: ["Guide to customs clearance in Saudi Arabia", "Everything you need to know about customs clearance for imported goods."] },
  { type: "warehousing", image: "/blog-images/IMG_8718.jpg", ar: ["حلول التخزين في الصين للمستوردين", "خيارات التخزين الآمن والاقتصادي للبضائع في الصين."], en: ["Warehousing solutions in China for importers", "Safe and economical storage options for goods in China."] },
  { type: "sourcing", image: "/blog-images/IMG_8719.jpg", ar: ["كيف تجد موردين موثوقين في ألبايا", "دليل عملي للبحث عن موردين موثوقين في مدينة ألبايا الصينية."], en: ["How to find reliable suppliers in Yiwu", "A practical guide to finding reliable suppliers in Yiwu, China."] },
  { type: "shipping", image: "/blog-images/IMG_8720.jpg", ar: ["أوقات الشحن من الصين للشرق الأوسط", "متوسط أوقات الشحن البحري والجوي من الصين لدول الخليج."], en: ["Shipping times from China to Middle East", "Average sea and air shipping times from China to Gulf countries."] },
  { type: "quality", image: "/blog-images/IMG_8721.jpg", ar: ["أنواع فحوصات الجودة المختلفة", "فهم أنواع فحوصات الجودة: فحص عشوائي، فحص كامل، فحص أثناء الإنتاج."], en: ["Different types of quality inspections", "Understanding quality inspection types: random inspection, full inspection, during production inspection."] },
  { type: "customs", image: "/blog-images/IMG_8722.jpg", ar: ["رموز HS وتأثيرها على الجمارك", "كيف تؤثر رموز HS على الرسوم الجمركية وكيفية اختيارها الصحيح."], en: ["HS codes and their impact on customs", "How HS codes affect customs duties and how to choose them correctly."] },
  { type: "warehousing", image: "/blog-images/IMG_8723.jpg", ar: ["تجميع الشحنات من موردين متعددين", "كيفية تجميع الشحنات من موردين مختلفين لتقليل التكلفة."], en: ["Consolidating shipments from multiple suppliers", "How to consolidate shipments from different suppliers to reduce costs."] },
  { type: "sourcing", image: "/blog-images/IMG_8724.jpg", ar: ["التفاوض مع الموردين الصينيين", "نصائح عملية للتفاوض الفعال مع الموردين الصينيين للحصول على أفضل الأسعار."], en: ["Negotiating with Chinese suppliers", "Practical tips for effective negotiation with Chinese suppliers to get the best prices."] },
  { type: "shipping", image: "/blog-images/IMG_8725.jpg", ar: ["التأمين على الشحنات الدولية", "أهمية التأمين على الشحنات وكيفية اختيار التغطية المناسبة."], en: ["Insurance for international shipments", "The importance of cargo insurance and how to choose the right coverage."] },
  { type: "quality", image: "/blog-images/IMG_8726.jpg", ar: ["فحص التغليف قبل الشحن", "لماذا فحص التغليف مهم لتجنب التلف أثناء الشحن."], en: ["Packaging inspection before shipping", "Why packaging inspection is important to avoid damage during shipping."] },
  { type: "customs", image: "/blog-images/IMG_8727.jpg", ar: ["التعامل مع الجمارك في الموانئ السعودية", "دليل للتعامل مع إجراءات الجمارك في موانئ جدة والدمام."], en: ["Dealing with customs in Saudi ports", "A guide to handling customs procedures in Jeddah and Dammam ports."] },
  { type: "warehousing", image: "/blog-images/IMG_8728.jpg", ar: ["إدارة المخزون في المستودعات الصينية", "كيفية إدارة مخزونك بشكل فعال في المستودعات الصينية."], en: ["Inventory management in Chinese warehouses", "How to effectively manage your inventory in Chinese warehouses."] },
];

export default function BlogPage() {
  const locale = useLocale();
  const ar = locale === "ar";
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const label = ar ? { eyebrow: "مركز المعرفة", title: "قرارات تجارة أفضل تبدأ بمعلومة أوضح.", intro: "أدلة عملية تساعدك على فهم التوريد والفحص والشحن قبل أن تتحول التفاصيل الصغيرة إلى تكلفة كبيرة.", search: "ابحث في الأدلة", all: "الكل", sourcing: "التوريد", shipping: "الشحن", quality: "الجودة", customs: "الجمارك", warehousing: "التخزين", featured: "دليل مختار", latest: "أحدث الأدلة", read: "اقرأ الدليل", cta: "لديك حالة خاصة؟ تحدث مع فريقنا" } : { eyebrow: "Knowledge center", title: "Better trade decisions start with clearer information.", intro: "Practical guides to help you understand sourcing, inspection, and shipping before small details become expensive problems.", search: "Search guides", all: "All", sourcing: "Sourcing", shipping: "Shipping", quality: "Quality", customs: "Customs", warehousing: "Warehousing", featured: "Selected guide", latest: "Latest guides", read: "Read guide", cta: "Have a specific case? Talk to our team" };
  const categoryLabels = { all: label.all, sourcing: label.sourcing, shipping: label.shipping, quality: label.quality, customs: label.customs, warehousing: label.warehousing };
    const categories = ["all", "sourcing", "shipping", "quality", "customs", "warehousing"] as const;
    const visible = posts.filter(post => { const content = ar ? post.ar : post.en; return (filter === "all" || post.type === filter) && content.join(" ").toLowerCase().includes(search.toLowerCase()); });
    const featured = ar ? posts[0].ar : posts[0].en;
    return <main className="site-palette bg-[#f8fbfc] text-[#102a43]">
      <section className="relative overflow-hidden bg-[#102a43] px-5 pb-24 pt-40 text-white sm:px-8 lg:px-12"><div className="absolute inset-0 bg-cover bg-center opacity-30" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=2000&q=85')" }} /><div className="absolute inset-0 bg-gradient-to-r from-[#071827] via-[#0d3048]/95 to-[#0d3048]/80" /><div className="relative mx-auto max-w-7xl"><p className="border-s-2 border-cyan-300 ps-4 text-sm font-bold uppercase tracking-[0.14em] text-cyan-200">{label.eyebrow}</p><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.05] sm:text-7xl">{label.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">{label.intro}</p><div className="relative mt-10 max-w-xl"><Search className="absolute start-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-300" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder={label.search} className="w-full rounded-xl border border-white/20 bg-white/10 py-4 pe-4 ps-12 text-white placeholder:text-slate-300 outline-none focus:border-cyan-300" /></div></div></section>
      <section className="relative z-10 mx-auto -mt-8 max-w-7xl px-5 sm:px-8 lg:px-12"><div className="flex gap-2 overflow-x-auto rounded-xl border border-[#dbe5eb] bg-white p-2 shadow-lg">{categories.map(item => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-5 py-3 text-sm font-bold ${filter === item ? "bg-[#102a43] text-white" : "text-[#607583] hover:bg-[#eaf2f4]"}`}>{label[item]}</button>)}</div></section>
      {filter === "all" && search === "" && <section className="mx-auto max-w-7xl px-5 pb-16 pt-20 sm:px-8 lg:px-12"><p className="text-sm font-bold uppercase tracking-[0.14em] text-cyan-700">{label.featured}</p><div className="mt-5 grid overflow-hidden rounded-2xl border border-[#dbe5eb] bg-white shadow-[0_16px_45px_rgba(16,42,67,0.08)] md:grid-cols-2"><div className="min-h-[300px] bg-cover bg-center" style={{ backgroundImage: `url('${posts[0].image}')` }} /><div className="flex flex-col justify-center p-7 sm:p-10"><BookOpen className="h-9 w-9 text-cyan-700" /><h2 className="mt-5 text-3xl font-black">{featured[0]}</h2><p className="mt-4 text-lg leading-8 text-[#5d7180]">{featured[1]}</p><Link href={`/${locale}/blog/${posts[0].type}`} className="mt-7 inline-flex items-center gap-2 font-bold text-cyan-700">{label.read}<ArrowRight className="h-4 w-4 rtl:rotate-180" /></Link></div></div></section>}
      <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="mb-9 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-cyan-700">Dinoora / Library</p><h2 className="mt-3 text-3xl font-black">{label.latest}</h2></div><span className="text-sm font-semibold text-[#718592]">{visible.length}</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((post, index) => { const content = ar ? post.ar : post.en; return <article key={post.type + index} className="group overflow-hidden rounded-2xl border border-[#dbe5eb] bg-white shadow-[0_10px_30px_rgba(16,42,67,0.04)] transition hover:-translate-y-1 hover:border-cyan-500/60"><div className="h-48 bg-cover bg-center transition duration-700 group-hover:scale-[1.03]" style={{ backgroundImage: `url('${post.image}')` }} /><div className="p-6"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-wider text-cyan-700"><span>{categoryLabels[post.type as keyof typeof categoryLabels]}</span><span className="flex items-center gap-1 text-[#81919a]"><Clock className="h-3.5 w-3.5" /> 6 min</span></div><h3 className="mt-4 text-xl font-bold leading-8">{content[0]}</h3><p className="mt-3 leading-7 text-[#617684]">{content[1]}</p><Link href={`/${locale}/blog/${post.type}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-700">{label.read}<ArrowRight className="h-4 w-4 rtl:rotate-180" /></Link></div></article>; })}</div></section>
      <section className="bg-[#dceff1] px-5 py-16 text-center sm:px-8"><ShieldCheck className="mx-auto h-8 w-8 text-cyan-700" /><h2 className="mt-5 text-3xl font-black">{label.cta}</h2><Link href={`/${locale}/contact`} className="mt-7 inline-flex items-center gap-3 rounded-lg bg-[#102a43] px-6 py-4 font-bold text-white hover:bg-[#1b9aaa]">{ar ? "تواصل معنا" : "Contact us"}<ArrowRight className="h-5 w-5 rtl:rotate-180" /></Link></section>
    </main>;
  }