"use client";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { useLocale } from "next-intl";
import { ArrowRight, BookOpen, Clock, Search, ShieldCheck } from "lucide-react";

const posts = [
  { id: "sourcing-1", type: "sourcing", image: "/blog-images/IMG_8706.jpg", ar: ["كيف تكتب طلب توريد يمنحك أسعاراً أفضل", "تعلم كيفية كتابة مواصفات دقيقة لطلب التوريد من الصين للحصول على عروض أسعار تنافسية من الموردين وتجنب سوء الفهم."], en: ["How to write a sourcing brief that gets better quotes", "Learn how to write precise specifications for your sourcing request from China to get competitive quotes from suppliers and avoid misunderstandings."] },
  { id: "shipping-1", type: "shipping", image: "/blog-images/IMG_8707.jpg", ar: ["بحري أم جوي؟ قرار الشحن يبدأ من طبيعة البضاعة", "دليل شامل لاختيار الشحن البحري أو الجوي من الصين بناءً على حجم البضاعة، الوقت المتاح، والميزانية."], en: ["Sea or air? Choose freight by cargo, not price alone", "A comprehensive guide to choosing sea or air freight from China based on cargo volume, available time, and budget."] },
  { id: "quality-1", type: "quality", image: "/blog-images/IMG_8708.jpg", ar: ["ما الذي يجب أن يتضمنه فحص ما قبل الشحن؟", "قائمة تفصيلية لفحص الجودة قبل الشحن تشمل المواصفات، الكمية، التغليف، الوثائق، والاختبارات العملية."], en: ["What should a pre-shipment inspection cover?", "A detailed checklist for pre-shipment quality inspection including specifications, quantity, packaging, documentation, and practical tests."] },
  { id: "customs-1", type: "customs", image: "/blog-images/IMG_8709.jpg", ar: ["المستندات التي تمنع التأخير في الجمارك", "تعرف على المستندات الأساسية للتخليص الجمركي: الفاتورة التجارية، قائمة التعبئة، شهادة المنشأ، ورموز HS."], en: ["The documents that prevent customs delays", "Learn about essential customs clearance documents: commercial invoice, packing list, certificate of origin, and HS codes."] },
  { id: "warehousing-1", type: "warehousing", image: "/blog-images/IMG_8710.jpg", ar: ["متى يكون تجميع الموردين خياراً أفضل؟", "تحليل تكلفة وفوائد تجميع الشحنات من موردين متعددين في الصين قبل الشحن إلى وجهتك."], en: ["When does multi-supplier consolidation make sense?", "Cost-benefit analysis of consolidating shipments from multiple suppliers in China before shipping to your destination."] },
];

export default function BlogPage() {
  const locale = useLocale();
  const ar = locale === "ar";
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const label = ar ? { eyebrow: "مركز المعرفة", title: "قرارات تجارة أفضل تبدأ بمعلومة أوضح.", intro: "أدلة عملية تساعدك على فهم التوريد والفحص والشحن قبل أن تتحول التفاصيل الصغيرة إلى تكلفة كبيرة.", search: "ابحث في الأدلة", all: "الكل", sourcing: "التوريد", shipping: "الشحن", quality: "الجودة", customs: "الجمارك", warehousing: "التخزين", featured: "دليل مختار", latest: "أحدث الأدلة", read: "اقرأ الدليل", cta: "لديك حالة خاصة؟ تحدث مع فريقنا" } : { eyebrow: "Knowledge center", title: "Better trade decisions start with clearer information.", intro: "Practical guides to help you understand sourcing, inspection, and shipping before small details become expensive problems.", search: "Search guides", all: "All", sourcing: "Sourcing", shipping: "Shipping", quality: "Quality", customs: "Customs", warehousing: "Warehousing", featured: "Selected guide", latest: "Latest guides", read: "Read guide", cta: "Have a specific case? Talk to our team" };
  const categoryLabels = { all: label.all, sourcing: label.sourcing, shipping: label.shipping, quality: label.quality, customs: label.customs, warehousing: label.warehousing };
    const categories = ["all", "sourcing", "shipping", "quality", "customs", "warehousing"] as const;
    const visible = posts.filter(post => { const content = ar ? post.ar : post.en; return (filter === "all" || post.type === filter) && content.join(" ").toLowerCase().includes(search.toLowerCase()); });
    const featured = ar ? posts[0].ar : posts[0].en;
    return <main className="site-palette bg-slate-950 text-white">
      <section className="relative overflow-hidden bg-[#102a43] px-5 pb-24 pt-40 text-white sm:px-8 lg:px-12"><div className="absolute inset-0 bg-cover bg-center opacity-30" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=2000&q=85')" }} /><div className="absolute inset-0 bg-gradient-to-r from-[#071827] via-[#0d3048]/95 to-[#0d3048]/80" /><div className="relative mx-auto max-w-7xl"><p className="border-s-2 border-cyan-300 ps-4 text-sm font-bold uppercase tracking-[0.14em] text-cyan-200">{label.eyebrow}</p><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.05] sm:text-7xl">{label.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200">{label.intro}</p><div className="relative mt-10 max-w-xl"><Search className="absolute start-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-300" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder={label.search} className="w-full rounded-xl border border-white/20 bg-white/10 py-4 pe-4 ps-12 text-white placeholder:text-slate-300 outline-none focus:border-cyan-300" /></div></div></section>
      <section className="relative z-10 mx-auto -mt-8 max-w-7xl px-5 sm:px-8 lg:px-12"><div className="flex gap-2 overflow-x-auto rounded-xl border border-indigo-500/20 bg-slate-900/95 p-2 shadow-lg shadow-indigo-500/10">{categories.map(item => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-5 py-3 text-sm font-bold ${filter === item ? "bg-indigo-600 text-white" : "text-slate-400 hover:bg-white/10"}`}>{label[item]}</button>)}</div></section>
      {filter === "all" && search === "" && <section className="mx-auto max-w-7xl px-5 pb-16 pt-20 sm:px-8 lg:px-12"><p className="text-sm font-bold uppercase tracking-[0.14em] text-cyan-400">{label.featured}</p><div className="mt-5 grid overflow-hidden rounded-2xl border border-indigo-500/20 bg-slate-900/95 shadow-[0_16px_45px_rgba(99,102,241,0.15)] md:grid-cols-2"><div className="relative min-h-[400px] aspect-video"><Image src={posts[0].image} alt={featured[0]} fill priority sizes="(max-width: 768px) 100vw, 50vw" className="object-contain" quality={90} /></div><div className="flex flex-col justify-center p-7 sm:p-10"><BookOpen className="h-9 w-9 text-cyan-400" /><h2 className="mt-5 text-3xl font-black">{featured[0]}</h2><p className="mt-4 text-lg leading-8 text-slate-300">{featured[1]}</p><Link href={`/${locale}/blog/${posts[0].id}`} className="mt-7 inline-flex items-center gap-2 font-bold text-cyan-400">{label.read}<ArrowRight className="h-4 w-4 rtl:rotate-180" /></Link></div></div></section>}
      <section className="mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="mb-9 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-cyan-400">Dinoora / Library</p><h2 className="mt-3 text-3xl font-black">{label.latest}</h2></div><span className="text-sm font-semibold text-slate-400">{visible.length}</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((post, index) => { const content = ar ? post.ar : post.en; return <article key={post.id + index} className="group overflow-hidden rounded-2xl border border-indigo-500/20 bg-slate-900/95 shadow-[0_10px_30px_rgba(99,102,241,0.15)] transition hover:-translate-y-1 hover:border-cyan-500/60"><div className="relative h-64 aspect-video transition duration-700 group-hover:scale-[1.03]"><Image src={post.image} alt={`${content[0]} - ${ar ? 'دينورا' : 'Dinoora'}`} fill sizes="(max-width: 768px) 50vw, 33vw" className="object-contain" quality={85} /></div><div className="p-6"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-wider text-cyan-400"><span>{categoryLabels[post.type as keyof typeof categoryLabels]}</span><span className="flex items-center gap-1 text-slate-400"><Clock className="h-3.5 w-3.5" /> 6 min</span></div><h3 className="mt-4 text-xl font-bold leading-8">{content[0]}</h3><p className="mt-3 leading-7 text-slate-300">{content[1]}</p><Link href={`/${locale}/blog/${post.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-400">{label.read}<ArrowRight className="h-4 w-4 rtl:rotate-180" /></Link></div></article>; })}</div></section>
      <section className="bg-slate-900/95 border-t border-indigo-500/20 px-5 py-16 text-center sm:px-8"><ShieldCheck className="mx-auto h-8 w-8 text-cyan-400" /><h2 className="mt-5 text-3xl font-black">{label.cta}</h2><Link href={`/${locale}/contact`} className="mt-7 inline-flex items-center gap-3 rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 px-6 py-4 font-bold text-white hover:shadow-lg hover:shadow-indigo-500/30 transition-all hover:-translate-y-0.5">{ar ? "تواصل معنا" : "Contact us"}<ArrowRight className="h-5 w-5 rtl:rotate-180" /></Link></section>
    </main>;
  }